test_1:
  TEST_ID: TEST-37228
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 2h
  sessions_per_node: 1
  tool: s3api
  operation: object_fix_size

test_2:
  TEST_ID: TEST-37229
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 2h
  sessions_per_node: 2
  tool: s3api
  operation: object_fix_size

test_3:
  TEST_ID: TEST-37231
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 20h
  sessions_per_node: 3
  tool: s3api
  operation: object_fix_size

test_4:
  TEST_ID: TEST-37232
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 1d
  sessions_per_node: 5
  tool: s3api
  operation: object_fix_size

test_5:
  TEST_ID: TEST-37233
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 1d
  sessions_per_node: 8
  tool: s3api
  operation: object_fix_size

test_6:
  TEST_ID: TEST-37234
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 2d
  sessions_per_node: 13
  tool: s3api
  operation: object_fix_size

test_7:
  TEST_ID: TEST-37235
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 2d
  sessions_per_node: 21
  tool: s3api
  operation: object_fix_size

test_8:
  TEST_ID: TEST-37236
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 4d
  sessions_per_node: 34
  tool: s3api
  operation: object_fix_size

test_9:
  TEST_ID: TEST-37237
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 5d
  sessions_per_node: 55
  tool: s3api
  operation: object_fix_size

test_10:
  TEST_ID: TEST-37238
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 5d
  sessions_per_node: 89
  tool: s3api
  operation: object_fix_size

test_11:
  TEST_ID: TEST-37239
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 5d
  sessions_per_node: 144
  tool: s3api
  operation: object_fix_size

test_12:
  TEST_ID: TEST-37241
  object_size:
    - 4kb
    - 8Kb
    - 16Kb
    - 32Kb
    - 64Kb
    - 128Kb
    - 256Kb
    - 512Kb
    - 1Mb
    - 2Mb
    - 4Mb
    - 8Mb
    - 16Mb
    - 32Mb
    - 64Mb
    - 128Mb
    - 256Mb
    - 512Mb
    - 1Gb
    - 2Gb
  min_runtime: 5d
  sessions_per_node: 233
  tool: s3api
  operation: object_fix_size
