test_1:
    TEST_ID: TEST-37367
    object_size: 4Gib
    part_range:
        start: 50
        end: 100
    min_runtime: 2h
    sessions: 5  # One object per session.
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_2:
    TEST_ID: TEST-37368
    object_size: 8Gib
    part_range:
        start: 100
        end: 200
    min_runtime: 2h
    sessions: 5
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_3:
    TEST_ID: TEST-37369
    object_size: 16Gib
    part_range:
        start: 200
        end: 300
    min_runtime: 20h
    sessions: 10
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_4:
    TEST_ID: TEST-37370
    object_size: 32Gib
    part_range:
        start: 300
        end: 400
    min_runtime: 1d
    sessions: 10
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_5:
    TEST_ID: TEST-37371
    object_size: 64Gib
    part_range:
        start: 400
        end: 500
    min_runtime: 1d
    sessions: 15
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_6:
    TEST_ID: TEST-37372
    object_size: 128Gib
    part_range:
        start: 500
        end: 600
    min_runtime: 2d
    sessions: 15
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_7:
    TEST_ID: TEST-37373
    object_size: 256Gib
    part_range:
        start: 600
        end: 700
    min_runtime: 2d
    sessions: 20
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_8:
    TEST_ID: TEST-37374
    object_size: 512Gib
    part_range:
        start: 700
        end: 800
    min_runtime: 4d
    sessions: 20
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_9:
    TEST_ID: TEST-37375
    object_size: 1Tib
    part_range:
        start: 800
        end: 1600
    min_runtime: 5d
    sessions: 25
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_10:
    TEST_ID: TEST-37376
    object_size: 2Tib
    part_range:
        start: 1600
        end: 3200
    min_runtime: 5d
    sessions: 25
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_11:
    TEST_ID: TEST-37377
    object_size: 4Tib
    part_range:
        start: 3200
        end: 6400
    min_runtime: 5d
    sessions: 30
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart

test_12:
    TEST_ID: TEST-37378
    object_size: 5Tib
    part_range:
        start: 6400
        end: 10000
    min_runtime: 5d
    sessions: 30
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart
