test_1:
    TEST_ID: TEST-36536
    object_size: 128Mib
    part_range:
        start: 20
        end: 25
    min_runtime: 4h
    sessions: 5
    range_read:
        start: 1byte
        end: 100byte
    tool: s3api
    operation: multipart_partcopy

test_2:
    TEST_ID: TEST-36537
    object_size: 256Mib
    part_range:
        start: 25
        end: 50
    min_runtime: 8h
    sessions: 5
    range_read:
        start: 100byte
        end: 200byte
    tool: s3api
    operation: multipart_partcopy

test_3:
    TEST_ID: TEST-36538
    object_size: 512Mib
    part_range:
        start: 50
        end: 75
    min_runtime: 4h
    sessions: 10
    tool: s3api
    range_read:
        start: 200byte
        end: 500byte
    operation: multipart_partcopy

test_4:
    TEST_ID: TEST-36539
    object_size: 1Gib
    part_range:
        start: 75
        end: 100
    min_runtime: 1d
    sessions: 10
    range_read:
        start: 500byte
        end: 1Kb
    tool: s3api
    operation: multipart_partcopy

test_5:
    TEST_ID: TEST-36540
    object_size: 4Gib
    part_range:
        start: 100
        end: 150
    min_runtime: 1d
    sessions: 15
    range_read:
        start: 1Kb
        end: 10Kb
    tool: s3api
    operation: multipart_partcopy

test_6:
    TEST_ID: TEST-36541
    object_size: 8Gib
    part_range:
        start: 150
        end: 200
    min_runtime: 2d
    sessions: 15
    range_read:
        start: 10Kb
        end: 100Kb
    tool: s3api
    operation: multipart_partcopy

test_7:
    TEST_ID: TEST-36542
    object_size: 16Gib
    part_range:
        start: 200
        end: 250
    min_runtime: 2d
    sessions: 20
    range_read:
        start: 100Kb
        end: 1Mb
    tool: s3api
    operation: multipart_partcopy

test_8:
    TEST_ID: TEST-36543
    object_size: 32Gib
    part_range:
        start: 250
        end: 300
    min_runtime: 3d
    sessions: 20
    range_read:
        start: 1Mb
        end: 10Mb
    tool: s3api
    operation: multipart_partcopy

test_9:
    TEST_ID: TEST-36544
    object_size: 64Gib
    part_range:
        start: 300
        end: 350
    min_runtime: 3d
    sessions: 25
    range_read:
        start: 10Mb
        end: 100Mb
    tool: s3api
    operation: multipart_partcopy

test_10:
    TEST_ID: TEST-36545
    object_size: 128Gib
    part_range:
        start: 350
        end: 400
    min_runtime: 5d
    sessions: 25
    range_read:
        start: 100Mb
        end: 150Mb
    tool: s3api
    operation: multipart_partcopy

test_11:
    TEST_ID: TEST-36546
    object_size: 256Gib
    part_range:
        start: 400
        end: 500
    min_runtime: 5d
    sessions: 30
    range_read:
        start: 150Mb
        end: 200Mb
    tool: s3api
    operation: multipart_partcopy

test_12:
    TEST_ID: TEST-36547
    object_size: 512Gib
    part_range:
        start: 500
        end: 600
    min_runtime: 7d
    sessions: 30
    range_read:
        start: 200Mb
        end: 1Gb
    tool: s3api
    operation: multipart_partcopy
