# s3 common parameters.
aws_cred_section: "default"
aws_path: "/root/.aws/credentials"
aws_config_path: "/root/.aws/config"
region: "US"
endpoint: "https://s3.seagate.com"
validate_certs: True
use_ssl: True
debug: False
