"product_family": "LC"
"product_type": "k8s"
#K8s based s3 server master details.
"nodes":
    - "hostname": "ssc-vm-g2-rhev4-3063.colo.seagate.com"
      "ip": ""
      "username": "root"
      "password": "seagate"
      "node_type": "master"
